---
title: "Log Marginal Likelihood vs. Sample Size"
output:
    prettydoc::html_pretty:
         toc: true
    theme: cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)


```

## 1-d Normal-Normal Example (unknown mean, known variance)

Setup: $X_1, \ldots, X_N \sim N(\mu, \sigma^2)$, $\mu \sim N\left( m_0, \tau^2 \right)$ 

Then, for $N = 50, 100, 200, 500, 1000, 10000$, we compute the marginal likelihood. 

```{r}
set.seed(1)
mu = 30
sigmasq = 4
m_0 = 0 
tau = 3

N_grid = c(50, 100, 200, 500, 1000, 10000)
iters = length(N_grid)

lil = numeric(iters) # store log marginal likelihood for each n

for (i in 1:iters) {
    
    N = N_grid[i]
    
    x = rnorm(N, mean = mu, sd = sqrt(sigmasq))
    xbar = mean(x)
    
    m_0 = 0 
    tau = 3
    
    lil[i] = log(sqrt(sigmasq)) - N * log(2 * pi * sqrt(sigmasq)) - 
        0.5 * log(N * tau^2 + sigmasq) - sum(x^2) / (2 * sigmasq) - 
        m_0^2 / (2 * tau^2) + 1 / (2 * (N * tau^2 + sigmasq)) * 
        (tau^2 * N^2 * xbar^2 / sigmasq + sigmasq * m_0^2 / tau^2 + 
             2 * N * xbar * m_0)
    
}

lil_df = data.frame(n = N_grid, lil = lil)
```

### log marginal likelihood vs. log n

```{r}
ggplot(lil_df, aes(log(n), lil)) + geom_point() + theme_bw()

lm(lil ~ log(n), lil_df)
```

### log marginal likelihood vs. n

```{r}
ggplot(lil_df, aes(n, lil)) + geom_point() + theme_bw()

lm(lil ~ n, lil_df)
```




## 2-d Normal-Inverse Gamma Example

```{r}
set.seed(1)
mu = 30
sigma_sq = 4
m_0 = 0
w_0 = 0.05
r_0 = 3
s_0 = 3

N_grid = c(50, 100, 200, 500, 1000, 10000)


#### generate data
LIL_n = numeric(length(N_grid))

for (n in 1:length(N_grid)) {
    
    N = N_grid[n]
    
    y = rnorm(N, mu, sqrt(sigma_sq))
    
    #### compute posterior parameters
    ybar = mean(y)
    m_n = (N * ybar + w_0 * m_0) / (N + w_0)
    w_n = w_0 + N
    r_n = r_0 + N
    s_n = s_0 + sum((y - ybar)^2) + (N * w_0 / (N + w_0)) * (ybar - m_0)^2
    
    
    #### compute true (log) marginal likelihood
    
    LIL_n[n] = -(N/2) * log(pi) + 0.5 * (log(w_0) - log(w_n)) + 
        lgamma(r_n / 2) - lgamma(r_0 / 2) + r_0 / 2 * log(s_0) - 
        r_n / 2 * log(s_n)
}


lil_df = data.frame(n = N_grid, lil = LIL_n)
```


### log marginal likelihood vs. log n

```{r}
ggplot(lil_df, aes(log(n), lil)) + geom_point() + theme_bw()

lm(lil ~ log(n), lil_df)
```



### log marginal likelihood vs. n
```{r}
ggplot(lil_df, aes(n, lil)) + geom_point() + theme_bw()

lm(lil ~ n,lil_df)
```



